name = "Puff"
description = "Puff theme for Hugo."
features = ["blog"]
homepage = "https://github.com/stuarthua/hugo-theme-puff"
license = "MIT"
licenselink = "https://github.com/stuarthua/hugo-theme-puff/blob/main/LICENSE"
min_version = "0.50"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal",
]

[params]
staticPrefix = ""
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []

[params.author]
homepage = "https://stuarthua.com"
name = "Stuart Hua"
