baseURL = "https://example.com"
languageCode = "en-us"
title = "Example Puff Blog"
theme = "puff"
DefaultContentLanguage = "en"
googleAnalytics = "G-XXXXXXXXXX"

[author]
  homepage = "https://blog.stuarthua.com/"
  name = "Stuart Hua"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
disqus = "stuarthua" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://stuarthua.com"
