title = "Example Blog"
baseURL = "https://example.com"
languageCode = "en-us"
DefaultContentLanguage = "en"

[author]
  homepage = "https://stuarthua.com/"
  name = "Stuart Hua"

[module]
  [[module.imports]]
    path = "github.com/stuarthua/hugo-theme-puff"

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1

  [languages.cn]
    contentDir = "content/cn"
    weight = 1

[menu]
  [[menu.main]]
    identifier = "categories"
    url = "/categories/"
    name = "categories"
    title = "Categories"
    weight = 1
  [[menu.main]]
    identifier = "tag"
    url = "/tags/"
    name = "tags"
    title = "Tags"
    weight = 2
  [[menu.main]]
    identifier = "about"
    url = "/about/"
    name = "about"
    title = "About"
    weight = 3

[services]
  [services.googleAnalytics]
    id = 'G-xxxxxx' # google analytics code
  [services.disqus]
    shortname = 'your disqus name' # disqus account name

[privacy]
  [privacy.googleAnalytics]
    disable = true # local run disable
    respectDoNotTrack = false
  [privacy.disqus]
    disable = true # local run disable

[params]
mainSections = ["posts", "categories", "tags"]
extraHead = ''
extraBody = ''
postHeaderContent = ""
postFooterContent = ""
lazyImage = true
twitterCards = true

[[params.socials]]
name = "rss"
link = "/index.xml"
[[params.socials]]
name = "About"
link = "https://stuarthua.com"
[[params.socials]]
name = "Github"
link = "https://github.com/stuarthua"
