baseURL = "https://stuarthua.com/"
title = "Stuart Hua's Blog"
languageCode = "en-us"
DefaultContentLanguage = "cn"

[module]
  [[module.imports]]
    path = "github.com/stuarthua/hugo-theme-puff"

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    weight = 1

[menu]
  [[menu.main]]
    identifier = "gallery"
    url = "/gallery/"
    name = "gallery"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    url = "/categories/"
    name = "categories"
    weight = 10
  [[menu.main]]
    identifier = "tag"
    url = "/tags/"
    name = "tags"
    weight = 20
  [[menu.main]]
    identifier = "about"
    url = "/about/"
    name = "about"
    weight = 30

[services]
  [services.googleAnalytics]
    id = 'G-xxxxxx' # google analytics code
  [services.disqus]
    shortname = 'your_disqus_name' # disqus account name

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = false
  [privacy.disqus]
    disable = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.x]
    disable = false
    enableDNT = false
    simple = false

[params]
# favicon = "/images/logo.png"
description = 'Example Website Description'
mainSections = ["posts", "categories", "tags"]
extraHead = ''
extraBody = ''
postHeaderContent = ''
postFooterContent = ''
lazyImage = true
twitterCards = true
googleAdsense = true
googleAdsenseClientId = "ca-pub-xxx"
googleAdsenseBannerSlotId = "xxx"
googleAdsenseArticleSlotId = "xxx"
  [params.author]
    name = "stuarthua"
    homepage = "https://stuarthua.com/"
  [[params.socials]]
    name = "rss"
    link = "/index.xml"
  [[params.socials]]
   name = "About"
   link = "https://stuarthua.com"
  [[params.socials]]
   name = "Github"
   link = "https://github.com/stuarthua"
